baseURL = "https://webninjasi.github.io/tfmrecords/" # "http://localhost:8080/"
languageCode = "en-us"
title = "TFM Records"
theme = "records"
Paginate = 24

[taxonomies]
	category = "categories"
	author = "authors"

[params]
	BookToC = false
	BookLogo = 'logo.png'
	BookSection = '*'
	BookDateFormat = 'January 2, 2006'
	BookSearch = false
