name: github pages

on:
  push:
    branches:
    - master

  repository_dispatch:
    types: [bot_update]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Checkout Hugo Data
        uses: actions/checkout@v6
        with:
          repository: TFMRecords/json-data
          path: ./data/
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Remove .git
        run: rm -r ./data/.git/

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.93.0'
          extended: true
      - run: node update-pages.js

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
